#!/usr/bin/python
import sys
import os
import ConfigParser
import urllib3

# this is a hack to get the hpe driver module
# and it's utils module on the search path.
cmd_folder = os.path.realpath(os.path.abspath("..") )
if cmd_folder not in sys.path:
     sys.path.insert(0, cmd_folder)

from hpe3parclient import client, exceptions

#config
config_file = "/etc/ganeti/extstorage/3par.conf"
config = ConfigParser.SafeConfigParser()
if not config.read(config_file):
  raise ConfigParser.Error("Unable to read config file")

host        = config.get('3par','host')
login       = config.get('3par','login')
password    = config.get('3par','password')
default_cpg = config.get('3par','default_cpg')

def ReadEnv():
  """Read the mandatory enviromental variables
  """

  if os.getenv("VOL_CNAME") is None :  
    name = os.getenv("VOL_NAME")
  else :
    name = os.getenv("VOL_CNAME")

  if name is None:
    sys.stderr.write('The environment variable VOL_NAME is missing.\n')
    sys.exit(1)

  size = int(os.getenv("VOL_SIZE")) // 1024
  if size is None:
    sys.stderr.write('The environment variable VOL_SIZE is missing.\n')
    sys.exit(1)

  cpg = os.getenv("EXTP_CPG")
  if cpg is None:
    cpg=default_cpg

  return (name, cpg, size)


def main():
  sys.stderr.write('Creation started...\n')

  env = ReadEnv()

  if env is None:
    sys.stderr.write('Wrong environment. Aborting...\n')
    sys.exit(1)

  vv_name,cpg, vv_size = env


  sys.stderr.write('name: %s, cpg: %s, size: %s\n' % (vv_name, cpg, vv_size))

  cl = client.HPE3ParClient(host, False, False, None, True)

  try: 
    cl.login(login,password)
  except exceptions.HTTPUnauthorized as ex:
       pprint.pprint("Login Failed")
  
  try:
    cl.createVolume(vv_name, cpg, vv_size)
  except exceptions.HTTPUnauthorized as ex:                                                                                                                                                                                    
       pprint.pprint("You must login first")                                                                                                                                                                                     
  except Exception as ex:                                                                                                                                                                                                      
       print(ex)

  cl.logout()


if __name__ == "__main__":
  sys.exit(main())

