#!/usr/bin/python -W ignore
import sys
import os
import socket
import ConfigParser
import urllib3
import time

# this is a hack to get the hpe driver module
# and it's utils module on the search path.
cmd_folder = os.path.realpath(os.path.abspath("..") )
if cmd_folder not in sys.path:
     sys.path.insert(0, cmd_folder)

from hpe3parclient import client, exceptions

sys.path.append("/usr/share/ganeti/default")
from ganeti import utils


#config
config_file = "/etc/ganeti/extstorage/3par.conf"
config = ConfigParser.SafeConfigParser()
if not config.read(config_file):
  raise ConfigParser.Error("Unable to read config file")

host        = config.get('3par','host')
login       = config.get('3par','login')
password    = config.get('3par','password')
default_cpg = config.get('3par','default_cpg')

def ReadEnv():
  """Read the mandatory enviromental variables
  """

  if os.getenv("VOL_NAME") is None :  
    sys.stderr.write('The environment variable VOL_NAME is missing.\n')
    sys.exit(1)
  else :
    name = os.getenv("VOL_NAME")

  if os.getenv("VOL_CNAME") is None :
    sys.stderr.write('The environment variable VOL_CNAME is missing.\n')
    sys.exit(1)
  else :
    cname = os.getenv("VOL_CNAME")


  return (name,cname)


def main():
  sys.stderr.write('Detach started...\n')

  vv_name, vv_cname = ReadEnv()

  sys.stderr.write('name: %s\n' % (vv_name))

  cl = client.HPE3ParClient(host, False, False, None, True)

  try: 
    cl.login(login,password)
  except exceptions.HTTPUnauthorized as ex:
       pprint.pprint("Login Failed")
  
  try:
    vlun = cl.getVLUN(vv_cname)
    export_host = socket.gethostname()
    cl.deleteVLUN(vv_cname,vlun['lun'],export_host,None)

    time.sleep(3)
    result = utils.RunCmd('multipath -F')
    cmd="for i in `pvs 2>&1 | grep 'read failed' | awk '{print $1}' | sed 's/://' | sed 's/\/dev\///' | uniq` ; do echo 1> /sys/block/$i/device/delete; done"
    result = utils.RunCmd(cmd)

  except exceptions.HTTPUnauthorized as ex:                                                                                                                                                                                    
       pprint.pprint("You must login first")                                                                                                                                                                                     
  except Exception as ex:                                                                                                                                                                                                      
       print(ex)

  cl.logout()


if __name__ == "__main__":
  sys.exit(main())

